apiVersion: v2
name: dbgate
description: A Helm chart for DbGate - Database management client
type: application
version: 0.1.7
appVersion: "7.2.3"
keywords:
  - database
  - sql
  - mysql
  - postgresql
  - mongodb
  - redis
home: https://dbgate.org/
icon: https://raw.githubusercontent.com/antiantiops/dbgate-helm-chart/main/dbgate/icon.png
sources:
  - https://github.com/dbgate/dbgate
maintainers:
  - name: antiantiops
